package com.contextapi.dtos;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * One exercise generated by the teacher for the student to answer.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExerciseDTO {
    private Long exerciseId;
    private Long contextId;
    private String contextContent;
    private String promptPt;
    
    private String variationNote;
    
    private String feedback;
    
    private Integer score;
    private boolean answered;
}
